import type { AISummary } from './types.js';
import type { DomainConfig } from './types.js';

/**
 * Converts hex color to rgba with specified opacity.
 * @param hex - Hex color code (e.g., "#FF6B6B")
 * @param opacity - Opacity value between 0 and 1
 * @returns RGBA color string
 */
function hexToRgba(hex: string, opacity: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

/**
 * Renders AI summary as ADHD-friendly HTML email.
 *
 * Structure:
 * - Domain header with colored border and background
 * - Title (h1) with colored bottom border
 * - Impact section (h2 💡) with explanation
 * - Key Points section (h2 📌) with 3 bullet points
 * - Action section (h2 🎯) with yellow highlight box
 *
 * All styles are inline for email compatibility.
 *
 * @param summary - AI-generated summary to render
 * @param domain - Domain configuration with label and color
 * @returns HTML string for email body
 *
 * @example
 * const html = renderHTML(summary, javaConfig);
 * // Returns formatted HTML with Java domain color
 */
export function renderHTML(summary: AISummary, domain: DomainConfig): string {
  const { title, impact, keyPoints, action } = summary;
  const { label, color } = domain;

  // Convert hex color to rgba for background (20% opacity)
  const bgColor = hexToRgba(color, 0.2);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">

  <!-- Domain Header -->
  <div style="background-color: ${bgColor}; border-left: 8px solid ${color}; padding: 20px; margin-bottom: 30px; border-radius: 4px;">
    <h3 style="margin: 0; color: ${color}; font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;">
      ${label} Newsletter
    </h3>
  </div>

  <!-- Title Section -->
  <h1 style="color: #222; font-size: 28px; font-weight: 700; margin: 0 0 20px 0; padding-bottom: 15px; border-bottom: 4px solid ${color};">
    ${escapeHtml(title)}
  </h1>

  <!-- Impact Section -->
  <h2 style="color: #444; font-size: 20px; font-weight: 600; margin: 30px 0 15px 0;">
    💡 Why This Matters
  </h2>
  <p style="font-size: 16px; line-height: 1.8; color: #555; margin: 0 0 25px 0; background-color: #fff; padding: 15px; border-radius: 4px; border-left: 3px solid #ddd;">
    ${escapeHtml(impact)}
  </p>

  <!-- Key Points Section -->
  <h2 style="color: #444; font-size: 20px; font-weight: 600; margin: 30px 0 15px 0;">
    📌 Key Takeaways
  </h2>
  <ul style="font-size: 16px; line-height: 1.8; color: #555; margin: 0 0 25px 0; padding-left: 25px; background-color: #fff; padding: 20px 20px 20px 45px; border-radius: 4px;">
    <li style="margin-bottom: 12px;">${escapeHtml(keyPoints[0])}</li>
    <li style="margin-bottom: 12px;">${escapeHtml(keyPoints[1])}</li>
    <li style="margin-bottom: 12px;">${escapeHtml(keyPoints[2])}</li>
  </ul>

  <!-- Action Section -->
  <h2 style="color: #444; font-size: 20px; font-weight: 600; margin: 30px 0 15px 0;">
    🎯 Next Step
  </h2>
  <div style="background-color: #fffacd; border-left: 4px solid #FF6B6B; padding: 20px; border-radius: 4px; margin: 0 0 30px 0;">
    <p style="font-size: 16px; line-height: 1.8; color: #333; margin: 0; font-weight: 500;">
      ${escapeHtml(action)}
    </p>
  </div>

  <!-- Footer -->
  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 14px;">
    <p style="margin: 0;">
      Newsletter Summary · Generated by AI
    </p>
  </div>

</body>
</html>
`.trim();
}

/**
 * Escapes HTML special characters to prevent XSS.
 * @param text - Text to escape
 * @returns Escaped HTML-safe string
 */
function escapeHtml(text: string): string {
  const htmlEscapes: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };

  return text.replace(/[&<>"']/g, (char) => htmlEscapes[char]);
}
